packages:
  - packages/*

catalog:
  "@aptabase/tauri": ^0.4.1
  "@lhlyu/vue-virtual-waterfall": 1.0.8
  "@octokit/rest": ^22.0.1
  "@pinia/colada": ^1.1.0
  "@sentry/vue": ^10.45.0
  "@tailwindcss/vite": ^4.2.2
  "@tauri-apps/api": ^2.10.1
  "@tauri-apps/plugin-fs": ^2.4.5
  "@tauri-apps/plugin-shell": ^2.3.5
  "@tauri-apps/plugin-sql": ^2.3.2
  "@tauri-apps/plugin-store": ^2.4.2
  "@types/linkify-it": ^5.0.0
  "@types/markdown-it": ^14.1.2
  "@types/semver": ^7.7.1
  "@vant/use": ^1.6.0
  "@vitejs/plugin-vue": ^6.0.6
  "@vitejs/plugin-vue-jsx": ^5.1.4
  "@vueuse/core": ^14.2.1
  browserslist: ^4.28.2
  dayjs: ^1.11.20
  dompurify: ^3.3.3
  es-toolkit: ^1.45.1
  jszip: ^3.10.1
  kysely: ^0.28.13
  kysely-dialect-tauri: ^1.2.1
  kysely-plugin-serialize: ^0.8.2
  lightningcss: ^1.32.0
  linkify-it: ^5.0.0
  lz-string: ^1.5.0
  markdown-it: ^14.1.1
  mitt: ^3.0.1
  motion-v: 2.0.1
  naive-ui: ^2.44.1
  pinia: ^3.0.4
  semver: ^7.7.4
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.2
  tailwindcss-safe-area-capacitor: ^0.5.1
  "tauri-plugin-better-cors-fetch": "github:wenxig/tauri-plugin-better-cors-fetch"
  tauri-plugin-sentry-api: ^0.5.0
  tlds: ^1.261.0
  typescript: ^5.9.3
  unplugin-vue-components: 32.0.0
  userscript-meta: ^1.0.1
  vant: ^4.9.22
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.16
  vite-plugin-externals: ^0.6.2
  vite-plugin-monkey: ^7.1.9
  vite-plus: ^0.1.16
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3.5.32
  vue-component-type-helpers: ^3.2.6
  vue-router: ^5.0.4

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
