/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cate': RouteRecordInfo<
      '/cate',
      '/cate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/[contentType]/[id]/[ep]': RouteRecordInfo<
      '/content/[contentType]/[id]/[ep]',
      '/content/:contentType/:id/:ep',
      { contentType: ParamValue<true>, id: ParamValue<true>, ep: ParamValue<true> },
      { contentType: ParamValue<false>, id: ParamValue<false>, ep: ParamValue<false> },
      | never
    >,
    '/hot': RouteRecordInfo<
      '/hot',
      '/hot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main': RouteRecordInfo<
      '/main',
      '/main',
      Record<never, never>,
      Record<never, never>,
      | '/main/home'
      | '/main/home/[id]'
      | '/main/home/hot'
      | '/main/home/random'
      | '/main/plugin'
      | '/main/plugin/config'
      | '/main/plugin/download'
      | '/main/plugin/list'
      | '/main/plugin/shop'
      | '/main/subscribe'
      | '/main/user'
    >,
    '/main/home': RouteRecordInfo<
      '/main/home',
      '/main/home',
      Record<never, never>,
      Record<never, never>,
      | '/main/home/[id]'
      | '/main/home/hot'
      | '/main/home/random'
    >,
    '/main/home/[id]': RouteRecordInfo<
      '/main/home/[id]',
      '/main/home/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/main/home/hot': RouteRecordInfo<
      '/main/home/hot',
      '/main/home/hot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/home/random': RouteRecordInfo<
      '/main/home/random',
      '/main/home/random',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/plugin': RouteRecordInfo<
      '/main/plugin',
      '/main/plugin',
      Record<never, never>,
      Record<never, never>,
      | '/main/plugin/config'
      | '/main/plugin/download'
      | '/main/plugin/list'
      | '/main/plugin/shop'
    >,
    '/main/plugin/config': RouteRecordInfo<
      '/main/plugin/config',
      '/main/plugin/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/plugin/download': RouteRecordInfo<
      '/main/plugin/download',
      '/main/plugin/download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/plugin/list': RouteRecordInfo<
      '/main/plugin/list',
      '/main/plugin/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/plugin/shop': RouteRecordInfo<
      '/main/plugin/shop',
      '/main/plugin/shop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/subscribe': RouteRecordInfo<
      '/main/subscribe',
      '/main/subscribe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/user': RouteRecordInfo<
      '/main/user',
      '/main/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search/[input]': RouteRecordInfo<
      '/search/[input]',
      '/search/:input',
      { input: ParamValue<true> },
      { input: ParamValue<false> },
      | never
    >,
    '/setting': RouteRecordInfo<
      '/setting',
      '/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/action/[plugin]/[key]': RouteRecordInfo<
      '/user/action/[plugin]/[key]',
      '/user/action/:plugin/:key',
      { plugin: ParamValue<true>, key: ParamValue<true> },
      { plugin: ParamValue<false>, key: ParamValue<false> },
      | never
    >,
    '/user/edit/[plugin]': RouteRecordInfo<
      '/user/edit/[plugin]',
      '/user/edit/:plugin',
      { plugin: ParamValue<true> },
      { plugin: ParamValue<false> },
      | never
    >,
    '/user/favourite': RouteRecordInfo<
      '/user/favourite',
      '/user/favourite',
      Record<never, never>,
      Record<never, never>,
      | '/user/favourite/[id]'
    >,
    '/user/favourite/[id]': RouteRecordInfo<
      '/user/favourite/[id]',
      '/user/favourite/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/user/history': RouteRecordInfo<
      '/user/history',
      '/user/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/recent': RouteRecordInfo<
      '/user/recent',
      '/user/recent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/cate.vue': {
      routes:
        | '/cate'
      views:
        | never
    }
    'src/pages/content/[contentType]/[id]/[ep].vue': {
      routes:
        | '/content/[contentType]/[id]/[ep]'
      views:
        | never
    }
    'src/pages/hot.vue': {
      routes:
        | '/hot'
      views:
        | never
    }
    'src/pages/main.vue': {
      routes:
        | '/main'
        | '/main/home'
        | '/main/home/[id]'
        | '/main/home/hot'
        | '/main/home/random'
        | '/main/plugin'
        | '/main/plugin/config'
        | '/main/plugin/download'
        | '/main/plugin/list'
        | '/main/plugin/shop'
        | '/main/subscribe'
        | '/main/user'
      views:
        | 'default'
    }
    'src/pages/main/home.vue': {
      routes:
        | '/main/home'
        | '/main/home/[id]'
        | '/main/home/hot'
        | '/main/home/random'
      views:
        | 'default'
    }
    'src/pages/main/home/[id].vue': {
      routes:
        | '/main/home/[id]'
      views:
        | never
    }
    'src/pages/main/home/hot.vue': {
      routes:
        | '/main/home/hot'
      views:
        | never
    }
    'src/pages/main/home/random.vue': {
      routes:
        | '/main/home/random'
      views:
        | never
    }
    'src/pages/main/plugin.vue': {
      routes:
        | '/main/plugin'
        | '/main/plugin/config'
        | '/main/plugin/download'
        | '/main/plugin/list'
        | '/main/plugin/shop'
      views:
        | 'default'
    }
    'src/pages/main/plugin/config.vue': {
      routes:
        | '/main/plugin/config'
      views:
        | never
    }
    'src/pages/main/plugin/download.vue': {
      routes:
        | '/main/plugin/download'
      views:
        | never
    }
    'src/pages/main/plugin/list.vue': {
      routes:
        | '/main/plugin/list'
      views:
        | never
    }
    'src/pages/main/plugin/shop.vue': {
      routes:
        | '/main/plugin/shop'
      views:
        | never
    }
    'src/pages/main/subscribe.vue': {
      routes:
        | '/main/subscribe'
      views:
        | never
    }
    'src/pages/main/user.vue': {
      routes:
        | '/main/user'
      views:
        | never
    }
    'src/pages/search/[input].vue': {
      routes:
        | '/search/[input]'
      views:
        | never
    }
    'src/pages/setting.vue': {
      routes:
        | '/setting'
      views:
        | never
    }
    'src/pages/user/action/[plugin]/[key].vue': {
      routes:
        | '/user/action/[plugin]/[key]'
      views:
        | never
    }
    'src/pages/user/edit/[plugin].vue': {
      routes:
        | '/user/edit/[plugin]'
      views:
        | never
    }
    'src/pages/user/favourite.vue': {
      routes:
        | '/user/favourite'
        | '/user/favourite/[id]'
      views:
        | 'default'
    }
    'src/pages/user/favourite/[id].vue': {
      routes:
        | '/user/favourite/[id]'
      views:
        | never
    }
    'src/pages/user/history.vue': {
      routes:
        | '/user/history'
      views:
        | never
    }
    'src/pages/user/recent.vue': {
      routes:
        | '/user/recent'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
