/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileFooter: typeof import('./src/components/file/FileFooter.vue')['default']
    FileIcon: typeof import('./src/components/file/FileIcon.vue')['default']
    FileList: typeof import('./src/components/file/FileList.vue')['default']
    FileRow: typeof import('./src/components/file/FileRow.vue')['default']
    FileSider: typeof import('./src/components/file/FileSider.vue')['default']
    Frame: typeof import('./src/components/Frame.vue')['default']
    LzMarkdown: typeof import('./src/components/base/LzMarkdown/LzMarkdown.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NTree: typeof import('naive-ui')['NTree']
    PathName: typeof import('./src/components/file/PathName.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateChecker: typeof import('./src/components/UpdateChecker.vue')['default']
  }
}
